kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: antascope-redis-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: ${ARTASCOPE_STORAGE_CLASS}
  namespace: ${ARTASCOPE_NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
