apiVersion: v1
kind: Secret
metadata:
  name: docker-register-auth
  namespace: ${ARTASCOPE_NAMESPACE}
data:
  .dockerconfigjson: ${ARTASCOPE_DOCKER_REGISTRY_AUTHJSON}
type: kubernetes.io/dockerconfigjson
