image: nas.magicqin.com:5555/magicqin/images/docker:19.03.3-compose

stages:
  - build
  - test
  - deploy

services:
- name: redis:5.0.7
  alias: redis

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

test:
  image:
    name: $CI_REGISTRY_IMAGE:latest
  variables:
    ARTASCOPE_ENV: test
  stage: test
  environment:
    name: test
  script:
    - /app/docker-entrypoint.sh test

deploy_stage:
  stage: deploy
  script:
    - docker-compose up -d
  variables:
    ARTASCOPE_ENV: staging
    ARTASCOPE_WEB_PORT: 31100
    ARTASCOPE_FLOWER_PORT: 31101
  environment:
    name: staging
  when: manual
  only:
    - master

deploy_prod:
  image: nas.magicqin.com:5555/magicqin/birdman/docker:19.03.3-kubectl
  stage: deploy
  script:
    - echo $CI_COMMIT_SHA
    - echo $KUBE_URL $KUBE_TOKEN $KUBE_NAMESPACE $KUBECONFIG
    - export KUBECONFIG=$KUBECONFIG
    - echo $KUBECONFIG
    - export NEW_IMAGE=nas.magicqin.com:5555/magicqin/birdman:$CI_COMMIT_SHA
    - echo $NEW_IMAGE
    - kubectl set image deployment birdman-app birdman-server=$NEW_IMAGE birdman-celery=$NEW_IMAGE birdman-web=$NEW_IMAGE --record -n birdman
  variables:
    BUGSBUNNY_ENV: prod
    BIRDMAN_WEB_PORT: 16666
  environment:
    name: prod
  when: manual
  only:
    - master
