repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
    exclude: .*\.md$
  - id: end-of-file-fixer
    exclude: .version
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7
