version: '3.7'
services:
  redis:
    image: redis:5.0.6
    container_name: artascope_redis
    restart: unless-stopped
    volumes:
      - artascope-redis:/data

  web:
    image: nas.magicqin.com:5555/magicqin/icloud-photo-downloader:latest
    container_name: artascope_web
    restart: always
    environment:
      - ARTASCOPE_ENV
      - TZ=Asia/Shanghai
    ports:
      - "${ARTASCOPE_WEB_PORT}:16666"
    command: ["web"]
    depends_on:
      - redis
      - celery_worker_main
      - celery_worker_upload
      - celery_worker_msg

  celery_worker_main:
    image: nas.magicqin.com:5555/magicqin/icloud-photo-downloader:latest
    container_name: artascope_celery_worker_main
    restart: always
    environment:
      - C_FORCE_ROOT=True
      - ARTASCOPE_ENV
      - TZ=Asia/Shanghai
    command: ["celery_worker_main"]
    depends_on:
      - redis

  celery_worker_upload:
    image: nas.magicqin.com:5555/magicqin/icloud-photo-downloader:latest
    container_name: artascope_celery_worker_upload
    restart: always
    environment:
      - C_FORCE_ROOT=True
      - ARTASCOPE_ENV
      - TZ=Asia/Shanghai
    command: ["celery_worker_upload"]
    depends_on:
      - redis

  celery_worker_msg:
    image: nas.magicqin.com:5555/magicqin/icloud-photo-downloader:latest
    container_name: artascope_celery_worker_msg
    restart: always
    environment:
      - C_FORCE_ROOT=True
      - ARTASCOPE_ENV
      - TZ=Asia/Shanghai
    command: ["celery_worker_msg"]
    depends_on:
      - redis

  celery_flower:
    image: nas.magicqin.com:5555/magicqin/icloud-photo-downloader:latest
    container_name: artascope_celery_flower
    restart: always
    environment:
      - C_FORCE_ROOT=True
      - ARTASCOPE_ENV
      - TZ=Asia/Shanghai
    ports:
      - "${ARTASCOPE_FLOWER_PORT}:5555"
    command: ["celery_flower"]
    depends_on:
      - redis

volumes:
  artascope-redis:

networks:
  artascope-net:
