kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: artascope
  name: artascope-app
  namespace: artascope
spec:
  replicas: 1
  revisionHistoryLimit: 10
  minReadySeconds: 20
  selector:
    matchLabels:
      k8s-app: artascope-app
  template:
    metadata:
      labels:
        k8s-app: artascope-app
    spec:
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: redis-data
          persistentVolumeClaim:
            claimName: antascope-redis-pvc
      containers:
        - name: artascope-redis
          image: redis:5.0.6
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: redis-data

        - name: artascope-web
          image: nas.magicqin.com:5555/magicqin/icloud-photo-downloader:latest
          command: ["/app/docker-entrypoint.sh", "web"]
          ports:
            - containerPort: 16666
              protocol: TCP
          env:
            - name: ARTASCOPE_ENV
              value: prod
            - name: TZ
              value: Asia/Shanghai
          livenessProbe:
            httpGet:
              port: 16666
              path: /user
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 16666
              path: /user
            initialDelaySeconds: 18
            periodSeconds: 2

        - name: celery-worker-main
          image: nas.magicqin.com:5555/magicqin/icloud-photo-downloader:latest
          command: ["/app/docker-entrypoint.sh", "celery_worker_main"]
          env:
            - name: ARTASCOPE_ENV
              value: prod
            - name: TZ
              value: Asia/Shanghai
            - name: C_FORCE_ROOT
              value: "true"
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume

        - name: celery-worker-upload
          image: nas.magicqin.com:5555/magicqin/icloud-photo-downloader:latest
          command: ["/app/docker-entrypoint.sh", "celery_worker_upload"]
          env:
            - name: ARTASCOPE_ENV
              value: prod
            - name: TZ
              value: Asia/Shanghai
            - name: C_FORCE_ROOT
              value: "true"
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume

        - name: celery-worker-msg
          image: nas.magicqin.com:5555/magicqin/icloud-photo-downloader:latest
          command: ["/app/docker-entrypoint.sh", "celery_worker_msg"]
          env:
            - name: ARTASCOPE_ENV
              value: prod
            - name: TZ
              value: Asia/Shanghai
            - name: C_FORCE_ROOT
              value: "true"

        - name: celery-flower
          image: nas.magicqin.com:5555/magicqin/icloud-photo-downloader:latest
          command: ["/app/docker-entrypoint.sh", "celery_flower"]
          ports:
            - containerPort: 5555
              protocol: TCP
          env:
            - name: ARTASCOPE_ENV
              value: prod
            - name: TZ
              value: Asia/Shanghai
            - name: C_FORCE_ROOT
              value: "true"

        - name: scheduler
          image: nas.magicqin.com:5555/magicqin/icloud-photo-downloader:latest
          command: ["/app/docker-entrypoint.sh", "scheduler"]
          env:
            - name: ARTASCOPE_ENV
              value: prod
            - name: TZ
              value: Asia/Shanghai

      serviceAccountName: artascope

---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: artascope
  name: artascope-service
  namespace: artascope
spec:
  type: NodePort
  ports:
  - name: http-web
    port: 16666
    targetPort: 16666
    nodePort: 31100
  - name: http-flower
    port: 5555
    targetPort: 5555
    nodePort: 31101
  selector:
    k8s-app: artascope-app

---
