---

apiVersion: v1
kind: Namespace
metadata:
  name: artascope

---

apiVersion: v1
kind: Secret
metadata:
  name: docker-register-auth
  namespace: artascope
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJuYXMubWFnaWNxaW4uY29tOjU1NTUiOiB7CgkJCSJhdXRoIjogImJXRm5kWE13TWpFNU9tSnZaVzVoTURJeE9RPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: artascope
  name: artascope
  namespace: artascope
imagePullSecrets:
  - name: docker-register-auth

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: artascope-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: artascope
  namespace: artascope

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: antascope-redis-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  namespace: artascope
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi

---
