#!/usr/bin/env bash

# set variable
ARTASCOPE_NAMESPACE=${ARTASCOPE_NAMESPACE-artascope}
ARTASCOPE_TIMEZONE=${ARTASCOPE_TIMEZONE-UTC}
ARTASCOPE_STORAGE_CLASS=${ARTASCOPE_STORAGE_CLASS-managed-nfs-storage}
ARTASCOPE_DOCKER_REGISTRY=${ARTASCOPE_DOCKER_REGISTRY-"https://index.docker.io/v1/"}
ARTASCOPE_DOCKER_REGISTRY_USERNAME=${ARTASCOPE_DOCKER_REGISTRY_USERNAME-""}
ARTASCOPE_DOCKER_REGISTRY_PASSWORD=${ARTASCOPE_DOCKER_REGISTRY_PASSWORD-""}
ARTASCOPE_DOCKER_REGISTRY_AUTH=`echo -n ${ARTASCOPE_DOCKER_REGISTRY_USERNAME}:${ARTASCOPE_DOCKER_REGISTRY_PASSWORD}|base64`
ARTASCOPE_DOCKER_REGISTRY_AUTHJSON=`echo -n {\"auths\":{\"${ARTASCOPE_DOCKER_REGISTRY}\":{\"auth\":\"${ARTASCOPE_DOCKER_REGISTRY_AUTH}\"}}} |base64`
ARTASCOPE_ADMIN_PORT=${ARTASCOPE_ADMIN_PORT-31100}
ARTASCOPE_FLOWER_PORT=${ARTASCOPE_FLOWER_PORT-31101}

echo ARTASCOPE_NAMESPACE: ${ARTASCOPE_NAMESPACE}
echo ARTASCOPE_TIMEZONE: ${ARTASCOPE_TIMEZONE}
echo ARTASCOPE_STORAGE_CLASS: ${ARTASCOPE_STORAGE_CLASS}
echo ARTASCOPE_DOCKER_REGISTRY: ${ARTASCOPE_DOCKER_REGISTRY}
echo ARTASCOPE_DOCKER_REGISTRY_USERNAME: ${ARTASCOPE_DOCKER_REGISTRY_USERNAME}
echo ARTASCOPE_DOCKER_REGISTRY_PASSWORD: ${ARTASCOPE_DOCKER_REGISTRY_PASSWORD}
echo ARTASCOPE_DOCKER_REGISTRY_AUTH: ${ARTASCOPE_DOCKER_REGISTRY_AUTH}
echo ARTASCOPE_DOCKER_REGISTRY_AUTHJSON: ${ARTASCOPE_DOCKER_REGISTRY_AUTHJSON}
echo ARTASCOPE_ADMIN_PORT: ${ARTASCOPE_ADMIN_PORT}
echo ARTASCOPE_FLOWER_PORT: ${ARTASCOPE_FLOWER_PORT}

mkdir build

echo start create k8s yaml...
for file in `ls ./template`
do
  echo handle $file...
  ARTASCOPE_NAMESPACE=${ARTASCOPE_NAMESPACE} \
  ARTASCOPE_TIMEZONE=${ARTASCOPE_TIMEZONE} \
  ARTASCOPE_STORAGE_CLASS=${ARTASCOPE_STORAGE_CLASS} \
  ARTASCOPE_DOCKER_REGISTRY=${ARTASCOPE_DOCKER_REGISTRY} \
  ARTASCOPE_DOCKER_REGISTRY_AUTHJSON=${ARTASCOPE_DOCKER_REGISTRY_AUTHJSON} \
  ARTASCOPE_ADMIN_PORT=${ARTASCOPE_ADMIN_PORT} \
  ARTASCOPE_FLOWER_PORT=${ARTASCOPE_FLOWER_PORT} \
  envsubst < ./template/$file > build/$file
done
echo create k8s done.
