kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: antascope-redis-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  namespace: artascope
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
