kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: artascope
  name: artascope-service
  namespace: artascope
spec:
  type: NodePort
  ports:
  - name: http-web
    port: 16666
    targetPort: 16666
    nodePort: 31100
  - name: http-flower
    port: 5555
    targetPort: 5555
    nodePort: 31101
  selector:
    k8s-app: artascope-app
